# Generated by Django 2.0 on 2017-12-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171220_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='linklist',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Rabbit Hole', max_length=50),
        ),
    ]
