# Generated by Django 2.0 on 2017-12-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171220_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Social NetworkingSocial Life', max_length=50),
        ),
        migrations.RemoveField(
            model_name='group',
            name='website',
        ),
        migrations.AddField(
            model_name='group',
            name='website',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.linklist'),
            preserve_default=False,
        ),
    ]
