# Generated by Django 2.0 on 2017-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171220_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Rabbit Hole', max_length=50),
        ),
        migrations.RemoveField(
            model_name='group',
            name='website',
        ),
        migrations.AddField(
            model_name='group',
            name='website',
            field=models.ManyToManyField(to='core.linklist'),
        ),
    ]
