# Generated by Django 2.0 on 2017-12-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171224_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Netflix and Chill', max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='website',
            field=models.ManyToManyField(blank=True, related_name='group_link', to='core.linklist'),
        ),
    ]
