# Generated by Django 2.0 on 2017-12-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171225_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='website',
        ),
        migrations.AddField(
            model_name='group',
            name='web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_content', to='core.linklist'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Social Life', max_length=50),
        ),
    ]
