# Generated by Django 2.0 on 2017-12-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171230_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='web',
            new_name='webpage',
        ),
    ]
