# Generated by Django 2.0 on 2017-12-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171230_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='webpage',
        ),
        migrations.AddField(
            model_name='linklist',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_content', to='core.group'),
        ),
    ]
