# Generated by Django 2.0 on 2018-01-04 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180103_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Work mode', max_length=50),
        ),
        migrations.AlterField(
            model_name='linklist',
            name='link',
            field=models.CharField(max_length=100, validators=[django.core.validators.URLValidator()]),
        ),
    ]
