# Generated by Django 2.0 on 2018-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180104_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='linklist',
            name='protocol',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS')], default='HTTP', max_length=5),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='random Creeps of The Internet', max_length=50),
        ),
    ]
