# Generated by Django 2.0 on 2018-01-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180105_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Amazon window Shopping', max_length=50),
        ),
        migrations.AlterField(
            model_name='linklist',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='linklist',
            name='protocol',
            field=models.CharField(choices=[('HTTP://', 'HTTP'), ('HTTPS://', 'HTTPS')], default='HTTP://', max_length=5),
        ),
    ]
