# Generated by Django 2.0 on 2018-01-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='version_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.CharField(default='v0.0.1', max_length=5)),
                ('version_name', models.CharField(default='New update', max_length=1000)),
                ('version_detail', models.TextField(default='Bugs Fixed, and improvements implemented.', max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
